<?php
/**
 * VAPTTest - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: wptest
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: f1aefd4f0bdf855f19a475ddf333a0bec67db20ddd1ceef6faaabfe9918dfd05
 */

$vapt_locked_config_data = '{\"build_id\":\"B260522-6b9f\",\"domain_pattern\":\"wptest\",\"domain_type\":\"standard\",\"tracking_mode\":\"local\",\"integrity_url\":\"http:\\/\\/vaptsecure.local\\/wp-admin\\/admin-ajax.php\",\"license\":{\"type\":\"trial\",\"auto_renew\":false,\"start\":1779702169,\"expires\":1780306969,\"renewal_count\":0},\"white_label\":{\"name\":\"VAPTTest\",\"slug\":\"vapttest\",\"description\":\"just some.. Description. Regenerated\",\"author\":\"Tanveer\",\"company\":\"Malik\",\"version\":\"1.0.1\",\"requires_at_least\":\"5.6\",\"requires_php\":\"7.4\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779702169,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = 'f1aefd4f0bdf855f19a475ddf333a0bec67db20ddd1ceef6faaabfe9918dfd05';
