<?php
/**
 * VAPTSecret - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: wptest
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 2157ec088659a5092252477fde709f9dc38fd2e1361de177e90ffced4ab5dcd1
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"wptest\",\"white_label\":{\"name\":\"VAPTSecret\",\"slug\":\"vaptsecret\",\"description\":\"\",\"author\":\"\",\"company\":\"\",\"version\":\"1.0.1\",\"requires_at_least\":\"5.6\",\"requires_php\":\"7.4\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779276458,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = '2157ec088659a5092252477fde709f9dc38fd2e1361de177e90ffced4ab5dcd1';
