<?php
/**
 * VAPTBuild - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: wptest
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 24e264599cb2b404a978a17890d8c688670bee7993a9ec6a016883012bbb1edd
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"wptest\",\"white_label\":{\"name\":\"VAPTBuild\",\"slug\":\"vaptbuild\",\"author\":\"Tanveer\",\"company\":\"Cosmic Technology\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779268356,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = '24e264599cb2b404a978a17890d8c688670bee7993a9ec6a016883012bbb1edd';
