<?php
/**
 * MyTest Standard - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: mytest.local
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 4797da267f4506e130beb2ddfe96df4de12713b898d55a5676d6797113f9606f
 */

$vapt_locked_config_data = '{\"build_id\":\"B260528-457d\",\"domain_pattern\":\"mytest.local\",\"domain_type\":\"standard\",\"tracking_mode\":\"local\",\"integrity_url\":\"http:\\/\\/vaptsecure.local\\/wp-admin\\/admin-ajax.php\",\"callback_test\":false,\"license\":{\"type\":\"trial\",\"auto_renew\":false,\"start\":1779970011,\"expires\":1780574811,\"renewal_count\":0},\"white_label\":{\"name\":\"MyTest Standard\",\"slug\":\"mytest-standard\",\"description\":\"\",\"author\":\"Tanveer\",\"company\":\"CosmicTechSol\",\"version\":\"1.0.0\",\"requires_at_least\":\"5.6\",\"requires_php\":\"8.3\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779970011,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = '4797da267f4506e130beb2ddfe96df4de12713b898d55a5676d6797113f9606f';
