<?php
/**
 * VAPT Security - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: vaptsecure
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: a0ccfaa08486e435db8d3f3935ff7b5639d23c02279537bd655ed475a748f793
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"vaptsecure\",\"white_label\":{\"name\":\"\",\"slug\":\"\",\"description\":\"\",\"author\":\"\",\"company\":\"\",\"version\":\"1.0.0\",\"requires_at_least\":\"5.6\",\"requires_php\":\"7.4\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779300330,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = 'a0ccfaa08486e435db8d3f3935ff7b5639d23c02279537bd655ed475a748f793';
