<?php
/**
 * VAPTSecurity - Domain Locked Configuration
 * 
 * This file is automatically generated.
 * It is locked to the domain pattern: hermasnet.com
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 5958f2a0e42e06e0f811bbd8249392646a97fc3d5f5bc0288d186953bbf0ce2e
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"hermasnet.com\",\"domain_type\":\"standard\",\"license\":{\"type\":\"demo\",\"auto_renew\":false,\"start\":1779335953,\"expires\":1780631953,\"renewal_count\":0},\"white_label\":{\"name\":\"VAPTSecurity\",\"slug\":\"vaptsecurity\",\"description\":\"\",\"author\":\"Tanveer Malik\",\"company\":\"Cosmic Technology Solution\",\"version\":\"1.0.2\",\"requires_at_least\":\"5.6\",\"requires_php\":\"7.4\"},\"settings\":{\"enable_cron\":0,\"rate_limit_max\":10,\"rate_limit_window\":1,\"validation_email\":0,\"validation_sanitization_level\":\"standard\",\"cron_protection\":0,\"cron_rate_limit\":60,\"enable_logging\":0,\"vapt_integration_cf7\":0,\"vapt_integration_elementor\":0,\"vapt_integration_wpforms\":0,\"vapt_integration_gravity\":0},\"generated_at\":1779335953,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = '5958f2a0e42e06e0f811bbd8249392646a97fc3d5f5bc0288d186953bbf0ce2e';
